name: Test / Build

on:
  push:
    branches:
    - '*'
  pull_request:
    branches:
    - '*'

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go_version: ['1.16', '1.17', '1.18']
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-go@v2
      with:
        go-version: ${{ matrix.go_version }}
    - run: go get -t -v ./...
    - run: go test -v -race ./...
  build:
    name: Build Docker image
    runs-on: ubuntu-latest
    needs: test
    steps:
    - uses: actions/checkout@v2
    - name: Prepare
      id: prepare
      run: |
        echo ::set-output name=version::${GITHUB_REF##*/}
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v1
      with:
        platforms: all
    - name: Set up Docker Buildx
      id: buildx
      uses: docker/setup-buildx-action@v1
      with:
        install: true
        version: latest
        driver-opts: image=moby/buildkit:master
    - name: Build
      uses: docker/build-push-action@v2
      with:
        context: .
        file: ./Dockerfile
        platforms: linux/amd64,linux/arm/v7,linux/arm64
        push: false
